###lesson 1: Lesson 1: Dividened Mind {unnumbered}

#분열된 마음
https://learn.constructivedialogue.org


#의견 불일치 경험
초저선량방사선(자연방사선 보다 낮은 수준)의 위해성이 없음에도 자꾸 위험하다고 주장하고 시위하는 사람들. 간단한 산수도 못하고 우기는 것이 답답하다.

#원시의 뇌
우리는 첨단 사회에 살고 있으나, 우리의 구석기적 뇌는 업데이트가 안됐다.

#정신의 지름길 Mental Shortcuts

#Our Divided Minds
머릿속에 분열이 진행된 적이 있는가?
  우리의 뇌는 두가지모듈이 있다.
1. 자동양식
2. 통제양식

Automatic Thinking 자동양식
- fast
- Unconscious
- Automatic
- Emotional

Controlled Thinking 통제양식
- Slow
- Conscious
- Efforful
- Logical

#Understanding Check
질문. Okaly, lets make sure you gor all of that. Which of the following are examples of automatic thinking?
1. Smiling when someone says something funny
2. Telling your favorite joke at a party
3. Recognizing your friend at a party
4. Clicking like on a social media post

정답. 1,3,4

1. 웃길 때 웃는 건 자동양식
2. 파티에서 농담하는 건 통제양식
3. 파티에서 친구를 알아보는 건 자동양식
4. 자동양식

#A Good Deal?
좋은 중고 차를 알아봤는데, 걸리는 점을 발견했다.
차 서류를 열었더니 차 전주인이 유명한 연쇄살인마라는 점을 알았다.
사겠습니까?
  
  나: 안 사겠다. 내게 안 좋은 일이 생겼을 때 괜히 차 핑계를 댈 것 같다. 더 열심히 벌어서 새 차를 사겠다.

#The Rider and Elephant, Pt. 1
대부분은 그 차를 안 사려고 한다.
서류 발견 후의 즉각적인 반응때문에.

역겨운 요인은 왜일까?
  
  그 답은 자동양식과 통제양식을 동시에 생각해야한다.
우리의 마음은 큰 코끼리에 탄 사람으로 비유할 수 있다.
코끼리는 자동, 사람은 통제.

#The Rider and Elephant, Pt.2
둘 사이의 불균형이 얼마나 강력한지를 기억하는 게 도움이 된다.
사람은 고삐를 쥘 수 있지만, 힘이 센 동물 위에 앉아있다.
대부분 힘이 센 동물에 따라가게 된다.
연쇄살인마의 차를 타지 않는 것은, 너의 코끼리가 말하고 있다.
(자동으로 반응했기때문)

#Intuitions First, Reasonin Second
자동양식은 우리의 생각에 큰 역할을 한다. 대개 직관이 우선이다.
본능적인 반응이 나올 때는 코끼리가 이긴 것이다.
논리적인 생각은 합리화하는 데 사용된다.
직관이 결정하고 논리가 정당화하는 것이 상당히 빠르기 때문에 알지못하고 그 결정을 논리가 했다고 착각을 하는 것이다. 하지만 실제는 직관이 정하는 것!!!!!!!!!!!!!!!!! 핵심내용

직관이 먼저 작동하고, 추론은 나중에 합리화.

#How we think
우리의 라이더는 변호사다!!!
  
#Autopilot
직관 자체가 나쁘다는 것은 아니다.
너무 빠르다보니 우리를 헷갈리게 할 때가 있는 것 뿐

# Condemn or Condone? Pt. 1
질문. 내가 좋아하는 사람과 그 이유
나. 유재석. 참 부지런한 것 같다.

친구가 위 인물이 잘못했다는 내용의 뉴스를 보냈다.
구체적인 근거는 없다.
너 어떻게 생각해? 라고 보냈을 때 내 반응은?
  
나. 그것이 사실 기반의 기사라면 실망하고 돌아서겠지만, 기사의 출처를 찾으려고 할 것 같다. 저거 오피셜이야? 하는 반응이 먼저 나올 것 같다.

#Condemn or Condone? Pt. 2
내가 잘 못 믿는 사람.
나. 말많은 개그맨들.

친구가 위 인물이 잘못했다는 내용의 뉴스를 보냈다.
구체적인 근거는 없다.
너 어떻게 생각해? 라고 보냈을 때 내 반응은?
  
나. 그럴 줄 알았다.

#Cognitive Biases

#Confirmation Bias 확증편향
확증편향이라는 것은 이미 갖고있는 신념과 일치하는 것은 쉽게 받아들이고 불일치하는 것은 거부하는 성향
확증편향은 어느 곳에나 존재한다. 우리의 신념과 일치하고 해당하는 부분만 찾아본다.

기존의 믿음과 일치하는 것은 잘 수용하되, 반대의 경우 거부하는 것을 확증편향이라 설명할 수 있다.

#Whose Facts?
우리의 코끼리는 기존의 직관, 느낌, 신념을 통해서 자동으로 정보를 걸러낸다.

#Life Hack
우리의 코끼리가 폭주하는 상황을 생각해봐라.
코끼리가 폭주하면 우리의 생각을 새로운 각도에서 바라봐야함.
Step1,2 잘 확인하기!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
#Practice
  수업이 있는데 생각과 맞아떨어질 때 모든 문제를 해결할 수 있을 것 같다!
  이런 상황에서 어떤 것이 확증편향에 대한 경고 징표이려나?
  
  정답은 1,3

#Lesson 1 Rec메
우리 뇌는 두가지 생각하는 시스템을 갖고 있고, 자동이나 통제양식이다.
우리의 논리적인 추론은 직관을 따른다.
우리의 추론은 일관적인 오류가 있다. 그리고 종종 알아채지 못한다.

요약본 다운로드 받기@!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
#Tour takeaways
  반드시 하나 기억해야할 것.
- 확증편향 / 인지편향
- 우리는 직관을 먼저 따르게 되고, 이를 합리화하기 위해 추론을 한다.
- 자동처리기능과 통제양식이 있다는 점

 우리의 삶에 어떻게 사용할까?
나.인생에 중대한 결정을 하게 될 때, 첫번째 선택은 분명 직관이 먼저 따를 것이니 계속 의심하고 추론하며 나 스스로 그저 정당화하고 있는 것은 아닌지 계속해서 생각해야한다.
 그렇다면 더욱 신중한 결정을 하게 되며 이는 긍정적인 결과로 이어지게 된다.


###Lesson2. Us and Them

주요키워드: 이중체계이론

추론체계보다 직관체계가 빠릅니다.
코끼리(직관)가 더욱 빠릅니다.
우리의 직관이 추론을 이끈다.

#Mind Reading
정치적 다른 견해의 사람들의 게임 얼마나 이해하는가?
폴리티컬리닝: 정치적편향

#How We Wdd Each Other
대부분이 퍼세션갭이 있다.

극단적인 기로에 놓이게 된다.

#The Implications
67%의 미국인들이 사회적으로 갈라지는 것에 대해 역겹게 생각했다.
분열되어있다고 하지만, 극단적으로 갈리는 것에 대해 부정적으로 생각.
극단적인 목소리에 지친 다수.

#Where Do Our Differences Come From?
도덕기반이론 Moral Foundations Theory
우리의 마음은 6가지의 맛을 느끼는 혀와 같다.

#Our Moral Intuitions
6가지의 도덕직관이 정보를 걸러내어 세상을 이해한다.

#Uncovering the Moral Foundations
도덕기반이론

- 돌봄 care
다른 사람을 돌봐주는 것, 위해끼치는 것을 막는 것이다.
친절과 자비에 근저에 있다.
돌봄기반을 중시하는 사람들은 공감이나 친절을 우선시한다.

- 공평 fairness
속이는 사람 싫어해요. 공평기반은 정의나 공평, 상호성의 근간이 된다.
- 자유 liberty
- 충성심 loyalty (가족)
내집단 충성
- 권한 authority (아버지)
- 순결 sanctity
존엄성, 신성함

세상은 직관(감정렌즈)으로 본다.

#Same Foundations, Different Applications
에이샤는 낙태 반대
마리아는 낙태 찬성

모든 기반을 이해하는 것이 똑같지 않아서 도덕기반의 가중치가 모두 다르다.
진보와 보수의 가중치가 달라 이런 점으로 인해
세상을 바라보는 관점이 달라질 수 있다.

###LESSON 3

#Warriors Lose
논쟁에서 이겼지만, 상대방의 마음을 잃는 상황이 되는데 얻는 것보다 잃는 게 더 많게 된다.
우리는 왜 워리어 마인드 셋을 하는가?

#Being Wrong
모든 사람들은 자신이 옳다는 느낌을 좋아한다. 
우리는 종종 틀리지만 깨닫지 못하는 상황이 많다.

#Embracing Not Knowing
깊이 있게 알지 못하는구나를 깨닫게 된다.
실제 알고 있는 것보다 덜 알고 있다는 사실을 아는 것이 좋은 것이다.

잘 알지 못한다는 것을 받아들여라

#Intellectual Humility
우리가 알고 있다는 것의 한계와 틀릴 수 있다는 것을 인정하는 것이 상당히 중요하다.
지적겸손한 사람들
- 틀렸다는 것을 받아들이는 게 삶의 이유
- 남들의 비판을 잘 수용한다.
- 내가 틀린 순간을 성장기회로 본다.

#Benefits of Intellectual Humility
지적 겸손해지면
호감도 및 만족도가 올라가고 더 행복하게 되고
어려운 대화나 갈등을 해결해나갈 수 있다.
그러려면 어떻게 해야하는가?

#Belief Updating, Pt. 1
껐다 켰다하는 스위치가 아닌, 디머스위치를 갖고 있는 것처럼 꺼지고 켜지고 둘만 있는 게 아닌 불의 밝기를 조절할 수 있는 것처럼 우리의 생각도 그렇게 할 수 있지 않을까?

#Belief Updating, Pt. 2
새로운 것이 나왔을 때 우리의 신념을 업데이트한다.
마음을 바꿀 자세가 되어있어야한다.

#Changing Your Mind
중요한 건 내가 틀릴 수 있고, 생각을 바꿀 수 있다는 가능성이 중요하다.
열린 자세로 임하기.
내 실력을 갱신할 수 있다는 마음가짐이 중요하다.

#Explorer Mindset
탐험가의 가장 큰 자세는 열린마음.
탐험가의 마음가짐을 가져라

#Asking Questions
탐험가적 마음가짐은 일상대화에서 어떻게 할 수 있을 것인가?
- 호기심을 가져라. /즉각적으로 반박하지 말고 궁금해해라.
질문을 하라는 것.

#Good and Bad Questions
조언이나 공격하는 듯한 질문은 하지말라.
너는 잘 몰라. 라는 식으로, ~좀 찾아봐라. 라는 조언의 형태.

#Constructive Questions
- 진짜 호기심
: 네가 한 얘기 조금 더 얘기해줄래?
- 마음이 열려있는가
: 열린 질문을 해라.
- 복잡함을 최대하라
- 어떠한 이야기를 끌어내라
- 말의 톤 자체에 궁금증을 갖고 있어라.

#이 레슨을 통해 인생에서 써먹을 수 있는 부분.
What's one thing you want to remember from this lesson?
- 상대방에게 질문함에 있어 항상 신중을 가해야겠다.

What's one way you might use this takeaway in your life?
- 조언이라는 변명 뒤의 공격을 조심해야겠다.


###Lesson 4: Storytelling

이야기는 사람들에게 중요하다.
이야기를 통해서 변화를 풀어나가는 것이 상당히 효과적이다

사고와 숫자에 대한 맥락을 제시한다.

#1122복습 
일상생활에서 선입견, 신념을 따르는 것만 바라보는 것: 확증편향
코끼리는 감정의 렌즈
사람들은 가중치를 잘못 적용하긴 하지만, 때에 따라서 신념과 일치시키기 위해 서로 다른 쟁점에 대해 적용하는 기준이 달라질 수 있음
확증편향을 극복하기 위해서 지적겸손이 필요함!

싸움꾼 마음가짐은 이기는 것이 최종목표
우리는 탐험가적 마음가짐을 가져야합니다.

#The Anatomy of a Story
분열적인 쟁점.
이야기를 할 때는 세 가지를 주의해서 하라 HIT

- 진정성: 솔직함때문에 공감할 수 있게 된다 공감할 때 갖고있는 감정이 들어가야한다. 공감할 수 있도록 진실된 이야기를 통해서 감정을 공유할 수 있게 해야한다.
- 중요성
- 요점

#Secondhand Stories
사례1. 신념에 영향을 준 뉴스스토리, 엄마가 13살짜리 아이를 총격사건때문에 잃었던 뉴스를 보고 가슴아파서 총기소지 반대 신념을 갖게 됐다.

사례2. 가족의 신념을 채택. 

사례3. 이민에 대해 생각하지 않았던 사람. 룸메이트가 에콰도르 출생, 2살 때 부모님이 미국으로 불법이민을 해옴. 미국에서 자라다보니 불법이민자의 신분이다보니 영주권의 지위가 불안. 룸메이트가 스트레스를 받아하기때문에 시민권을 주는 것이 얼마나 중요한가를 느끼게 됨.

사례4. 존중하는 사람들이 신념에 영향을 미치는 경우.

#The Burden of Stories
이야기를 하는 것은 좋은 도구.
건설적인 대화를 할 때 중요한 소양.
이야기의 힘을 간과해서는 안되고 중요하다.

이야기를 할 때 구체적인 사건을 넣어서 전달하는 것이 효과적인 전달법이 된다. 설득력있고 호소력있게 들린다.

#Responding to Stories
이야기를 하는 것만큼이나 듣는 것도 중요하다.
끼어들고 싶거나 비교하려는 욕구가 들지만, 이럴 때일수록 상대방의 이야기 할 기회를 주고 그 이야기를 깊숙히 들으며 상호이해해야한다.

진정으로 듣고있다는 것을 사람들이 어떻게 알게 할까?

#How to Respond
- 반응 제시, 공유하고싶은 열린 마음을 표시하기. 인정하기.
- 공감하기. 같은 말 미러링해주기.
- 재진술하기. 미러링과 비슷하지만 조금 다르다. 그 사람이 말한 걸 이해하고 풀어서 다른 식으로 말하기
- 공감하기. 감정에 공감한다는 것을 표현하기. 그사람이 느끼는 감정을 함께 느끼도록 해보기.

상대방이 무슨 말을 했는지를 이해하고 상대방의 말을 반복하고, 인정하고, 공감하기.

#복습 
닫힌 질문은 예, 아니오만 나오는 질문
우리는 열린 질문을 해야한다.

논리와 사실만으로는 설득이 어렵다.
따라서 감성소구를 건드려야한다.

기억해야할 네가지
- 고맙고 감사한 마음을 표현하라. 상대방을 인정해줘라.
- 같은 말로 반응을 해준다.
- 재진술하기. 미러링과는 다릅니다. 의미를 풀어서 전달하기.
- 공감. 함께 느끼기. 함께 느꼈다는 것을 상대방에게 알려주기.

#100% Elephant
스트레치존: 화들짝 놀라진 않지만, 그냥 가만히 있는 느낌.
패닉존: 화들짝 놀라서 질 것 같은 느낌이 드는 것

코끼리는 직관. 우리의 뇌는 기본적으로 직관을 따른다.
코끼리가 날뛸 대 이성적인 추론은 필요가 없다.
이때 패닉존에 있는 코끼리를 스트레치 존으로 끌고 들어가야함.
이때 위의 네가지 방법을 사용하면 된다.

#Detect - Pause - Redirect
패닉존에 들어갔을 때 써야할 세가지 방법.
1. 패닉상태인 걸 깨닫기
2. 일시정지
3. 패닉존에서 빠져나갈 방법 궁리하기
감정이 확 북받칠 때 숫자 3을 세라고 하는 것과 비슷한 맥락.
그렇지 않으면 실수를 하게 되어있다. - 잠깐 쉬어라.

#The Moldy Fridge Episode
상한음식을 그대로 넣어놓은 상황.
이렇게 하면 어떻게 하냐고 패닉존에 들어온 Amir

#The Fight, Flight, or Freeze Response
우리 몸이 위험을 지각했을 때 보이는 반응

전투모드
도망모드
얼음모드 : 피식자들에게 살아남는 데 도움이 된다. 포식자가 나보다 빠르면 싸워도 잡혀먹힌다. 하지만, 도망가도 잡혀먹힘. 이럴 때 모른 체 가만히 있으며 운에 맡긴다. 이것이 얼음모드.

즉각적으로 반응한다.
아드레날린이 순간적으로 분비해서 세가지 중 하나로 몸은 작동한다.

분노일 때는 피가 피부로 몰린다.
공포일 때는 피가 피부에서 쫙 빠진다. ->피부가 하얗게 질린다.

분노는 내가 통제할 수 있고 이길 수 있다고 판단할 때 나오는 감정이지만 공포는 주변상황을 평가했을 때, 질 것이라고 판단할 때 나오는 감정. 

잠시나마 기수의 기능을 잃게 한 후 코끼리의 난리부르스.

#Detect
인간은 메타인지를 보유 중.
내가 패닉상태에 있다는 것을 아는 것이 제일 중요하다.
코끼리는 패닉상태에 있단 것을 모르고 기수를 셧다운 시킴.

건망증과 치매의 차이
건망증은 까먹었다는 것을 알고 치매는 까먹었다는 사실조차 모름.

#Amir's Panic Zone
열받아서 기분 나빠진 Amir

#Javi's Panic Zone
냉장고에 넣었던 Javi
자기가 잘못했음에도 화난 Amir을 마주치고 깜짝 놀라서 손발에 땀도 나고 긴장했다. 얼어붙음.

#Pause
잠깐 멈추는 것이 중요하다.
1단계, 패닉존에 들어왔을 때 화를 냈을 때 내가 후회할 것이라는 걸 깨달으면 좋다.
그냥 멈추는 것이 아니라 심호흡을 하는 것이 중요.
1,2,3 세고 쉬는 것이 중요.
복식호흡해야함. ->부교감 신경계의 활성화
아드레날린과같은 교감신경계를 가라앉히는 것이 부교감신경계.

#Techniques for Pausing
- 숨 깊게 쉬기
- 자신의 감각에 집중해 현재를 끌어올리기
- 생각과 느낌에 관찰하기
- 스스로에게는 잘했다고 긍정적인 칭찬해주기.

#Know Your Limits
상대방은 진정이 되지 않을 수도 있다. 미쳐날뛸 수도 있다는 것.

#Own Your Part
상대방은 계속 흥분해있더라도, 나의 일을 해야한다는 것.
그럴 때일수록, 변명거리를 찾거나 인정하지 않으려는 상황을 피하고
나에 대해서 내가 무엇을 해야할지를 확실히 파악하기.
한계를 딛고 나아갈 수 있도록하기.

#Express Care
나는 어떻게 느끼고 있어. 하는 정도에서 나아가
그래도 내가 너에 대해서 돌보는 마음이 있다는 것을 표현하기.

#Address the Issue
쟁점에 대해 대화해야하는 상황에서
 Behaviors. 어떤 행동을 할 것인가 할 때, 상대방의 행동에 대한 해석보다는 그 행동 자체를 이야기해라. 너 이기적인애야!하고 해석을 이야기하지말고, 그 행동 자체를 언급해야함.
 Impact. 그 행동이 나에게 어떤 영향을 미쳤는지 이야기하기.
 Needs 내가 상대방에게 원하는 것을 이야기하기.
 
#Take a Break
잠깐 쉬어라. 코끼리는 한두시간만에 진정되지 않는다.
내일 다시 이야기하자!

#Life Hack
놀랐을때나 어려워할 때 어떻게 하는지 알 수 있겠나. 알려달라고 말하기.
나의 패닉존 모먼트에 그들이 어떻게 반응해야하는지 말해줄 수 있다.
친구들에게 내가 어떻게 반응했는지, 너는 어떻게 반응하는지 친구들에게 확인해보라!

#Lesson 5 Recap
우리 뇌는 자동반응한다. 싸우거나 도망치거나 얼거나.
통제하려면 우리는 방법을 깨달아야한다.

